# Generated by Django 5.1.1 on 2024-11-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InstructorCourse",
            fields=[
                ("course_id", models.AutoField(primary_key=True, serialize=False)),
                ("instructor_id", models.IntegerField(default=0)),
                ("program_id", models.IntegerField(default=0)),
                ("course_code", models.TextField(blank=True, null=True)),
                ("course_name", models.TextField(blank=True, null=True)),
                ("department", models.TextField(blank=True, null=True)),
                ("credit_hours", models.IntegerField(blank=True, null=True)),
                ("prerequisites", models.JSONField(blank=True, null=True)),
                ("school_year", models.TextField(blank=True, null=True)),
                ("semester", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "instructor_course",
            },
        ),
        migrations.CreateModel(
            name="InstructorData",
            fields=[
                ("instructor_id", models.AutoField(primary_key=True, serialize=False)),
                ("college_id", models.IntegerField(default=0)),
                ("last_name", models.CharField(default="", max_length=255)),
                ("first_name", models.CharField(default="", max_length=255)),
                (
                    "middle_initial",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[("regular", "Regular"), ("cos", "COS")],
                        default="regular",
                        max_length=10,
                    ),
                ),
                ("qualified_course", models.JSONField(default=dict)),
                ("availability_days", models.JSONField(default=list)),
                ("availability_times", models.JSONField(default=list)),
            ],
            options={
                "db_table": "instructors_data",
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("program_id", models.AutoField(primary_key=True, serialize=False)),
                ("college_id", models.IntegerField()),
                ("program_code", models.TextField(blank=True, null=True)),
                ("program_name", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Program",
            },
        ),
    ]
